### ISSUE TITLE
Error: no root on click

### ISSUE THREAD

**Issue by adgower** [bumbeishvili/org-chart#311]
**Describe the bug**
When I click on a node it throws this error in the console.

**To Reproduce**
1. Click a node
2. View console

**Expected behavior**
I except no console error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 117

**Smartphone (please complete the following information):**

**Additional context**
Error:
```
stratify.js:77  Uncaught (in promise) Error: no root
    at Object.stratify [as generateRoot] (stratify.js:77:22)
    at OrgChart.setLayouts (d3-org-chart.js:1411:28)
    at OrgChart.render (d3-org-chart.js:594:14)
    at renderChart (StructurePage.vue:112:6)
    at StructurePage.vue:157:5
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1702:16)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at job (runtime-core.esm-bundler.js:1765:14)
```

Quasar/Vue 3 app:
```
const renderChart = (data) => {
  const chart = new OrgChart()

    .container(orgChartContainer.value) // use the ref
    .data(data)

    .nodeContent((node) => {
      const { id, name, type } = node.data;

      const backgroundColorClass = Dark.isActive ? 'bg-dark' : 'bg-white';

      // console.log(node.depth);
      // example add child/node
      //       <button
      //   onclick="chart.addNode({id:'child',parentId:'100',name:'test',_centered:true}).render()"
      // >
      //   Add node to the root
      // </button>
      // to remove a node
      // chart.removeNode

      // i want to set a color to indicate the depth: root, location ,department, division
      // const color = colors[d.depth % colors.length];

      return `
        <div
          style="
            border: 1px solid #ccc;
            height: ${node.height}px;
            display: flex;
            align-items: center;
            justify-content: center;
          "
          data-node-id="${id}"
          class="rounded-borders q-pa-md ${backgroundColorClass}"
        >

        <div>
          <div class="text-h6 text-center">
            ${name}
          </div>
          <div class="text-caption text-center">
            ${type ? type : ''}
            </div>
        </div>

        </div>
      `;
    })
    .render()
    .expandAll();

  // Add click event listener to nodes
  d3.selectAll('.node').on('click', (event) => {
    const nodeId = event.target.dataset.nodeId;

    if (!nodeId) {
      return;
    }

    // center the node
    chart.setCentered(nodeId).render();

    showNodeDetails(nodeId);

    // TODO: add functions for handling with try and click root node
    // TODO: need to modify dialog to handle when click on division node that doesn't have option to create child.
  });
};
```

**Comment by bumbeishvili** [comment]
@adgower can you provide an online sample with the issue reproduced?

You can fork this sample
https://stackblitz.com/edit/vue-wx7syy?file=src%2FChart.js
