### ISSUE TITLE
linkUpdate.transition is not a function     at OrgChart.update (d3-org-chart.js:924:1)

### ISSUE THREAD

**Issue by ManimaranN** [bumbeishvili/org-chart#434]
@bumbeishvili  while integrating with d3-org-chart with my  angular project i am getting an error 
linkUpdate.transition is not a function
    at OrgChart.update (d3-org-chart.js:924:1)

please find the version i am currently using
 "d3": "^6.6.0",
 "d3-org-chart": "^3.1.1",

**Comment by AjayTechEnthusiast** [comment]
@bumbeishvili I am also facing the same issue

**Comment by bumbeishvili** [comment]
@ManimaranN  @AjayTechEnthusiast  can you provide stackblitz example with the issue reproduced?

You can extend this sample - https://stackblitz.com/edit/angular-ivy-gneris?file=src%2Fapp%2Fapp.component.ts
